#============================================================================================================
# C O P Y R I G H T
#------------------------------------------------------------------------------------------------------------
# copyright (C) 2025 Robert Bosch GmbH and Cariad SE. All rights reserved.
#============================================================================================================

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rayClusterName: "ray-cluster"
teamNamespace: "argo-dev"
rayVersion: '2.43.0'

headGroupSpec:
  rayStartParams:
    # Setting "num-cpus: 0" to avoid any Ray actors or tasks being scheduled on the Ray head Pod.
    num-cpus: "0"
  # Pod template
  template:
    metadata: # Pod metadata
        labels: {}
    spec:
      containers:
      # The Ray head container
      - name: ray-head
        image: rayproject/ray:2.43.0
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: gcs
        - containerPort: 8265
          name: dashboard
        - containerPort: 10001
          name: client
        - containerPort: 8080
          name: metrics
        - containerPort: 22
          name: ssd
        resources:
          limits:
            cpu: "1"
            memory: "2G"
          requests:
            cpu: "1"
            memory: "2G"
        env:
          - name: RAY_enable_autoscaler_v2 # Pass env var for the autoscaler v2.
            value: "1"
      restartPolicy: Never # No restart to avoid reuse of pod for different ray nodes.

workerGroupSpecs:
  - groupName: sample-cpu-worker-group
    replicas: 0
    minReplicas: 0
    maxReplicas: 3
    rayStartParams: {}
    # Pod template
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.43.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1G"
            requests:
              cpu: "1"
              memory: "1G"
        restartPolicy: Never # Never restart a pod to avoid pod reuse