apiVersion: v1
kind: Pod
metadata:
  name: ray-head
  namespace: argo-dev
  labels:
    app: ray
    role: head
spec:
  containers:
  - name: ray-head
    image: ray-ssh:latest  # Make sure this image is available in your registry or built on your node
    imagePullPolicy: Always
    ports:
      - containerPort: 22      # SSH
      - containerPort: 6379    # Ray Redis
      - containerPort: 8265    # Ray Dashboard
      - containerPort: 10001   # Ray Client
    env:
      - name: RAY_HEAD
        value: "1"
