#============================================================================================================
# C O P Y R I G H T
#------------------------------------------------------------------------------------------------------------
# copyright (C) 2022 Robert Bosch GmbH and Cariad SE. All rights reserved.
#============================================================================================================

# Argo ui service account secret
apiVersion: v1
kind: Secret
metadata:
  name: argo-ui-sso-delegation-token
  namespace: argo-dev
  annotations:
    kubernetes.io/service-account.name: argo-dev
type: kubernetes.io/service-account-token
